### ISSUE TITLE
How far off is a working prototype? 

### ISSUE THREAD

**Issue by unhott** [sagemathinc/JSage#3]
Hello! 

I am brought here by this inquiry: 
https://community.starboard.gg/t/sage-blocks/126/3

I can see that this is a new project but extremely active and I am wondering how far off are you from a working prototype? And what might that look like? 
I've never used Sage or SageMath before so I'm not personally familiar with it, and as a result do not know what to look for, even if I were to succeed in building it. But I am nonetheless interested in cool technologies! 
:)

**Comment by williamstein** [comment]
There is a working prototype of something that might be slightly useful and feel "sage like" (in a VERY small way), but it only runs in node.js.   To try that out, see https://www.npmjs.com/package/@jsage/jpython

Very briefly, if you have a recent version of Nodejs installed, type this in a terminal
```
npx --package=@jsage/jpython jsage
```
and it will download and install and run a working prototype.
```
jsage: 2/3 + 4/5
22/15
jsage: 2^100
1267650600228229401496703205376
jsage: factor.factorTrialDivision(2021)
[{'p': 43, 'e': 1}, {'p': 47, 'e': 1}]
jsage: pari.init()
[object Promise]
jsage: pari.exec('factor(2021930823094820398402834)')
[              2 1]
[            359 1]
[        5796517 1]
[485819267362339 1]
jsage:  3^1000
1322070819480806636890455259752144365965422032752148167664920368226828597346704899540778313850608061963909777696872582355950954582100618911865342725257953674027620225198320803878014774228964841274390400117588618041128947815623094438061566173054086674490506178125480344405547054397038895817465368254916136220830268563778582290228416398307887896918556404084898937609373242171846359938695516765018940588109060426089671438864102814350385648747165832010614366132173102768902855220001
```

This is 100% using WebAssembly and Javascript, and there's no fundamental reason that it can't be made to work in a web browser soon.  I've been meaning to make it work in browser, but just haven't got to it.

Personally, one of the interesting things I've been writing for this is a Python --> Javascript compiler, which makes it so you can write python code but benefit from the speed and environment of a Javascript JIT.  Also, I've added in some hooks to it to make it more math friendly, so several of the special features of the "Sage preparser" work, but instead of a hacky preparser, this is done properly with a syntax tree.

Just to be clear, right now this is entirely a **totally for fun** side project, so no guarantees about anything.
